site_name: OI Knowledge Base
site_url: https://your-site.com
repo_url: https://github.com/yourusername/your-repo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - toc.integrate
  palette:
    primary: indigo   # 主色调
    accent: blue      # 强调色
  font:
    text: Roboto      # 正文字体
    code: Fira Code   # 代码字体

extra_css:
  - stylesheets/extra.css  # 自定义CSS

nav:
  - 首页: index.md
  - 算法:
    - 基础算法: algorithms/basic.md
    - 动态规划: algorithms/dp.md
  - 数据结构:
    - 栈和队列: data-structures/stack-queue.md
    - 树: data-structures/tree.md

plugins:
  - search
  - mkdocstrings
